name: Platform IO CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        environment: [esp32cam-release, esp32cam-debug]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'      
    
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO Core
        run: python -m pip install platformio

      - name: Build firmware -e ${{ matrix.environment }}
        run: platformio run -e ${{ matrix.environment }}

      - name: Upload firmwares
        uses: actions/upload-artifact@v4
        with:
          name: firmwares.zip
          path: .pio/build/*/*.bin